openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api-v1
paths:
  /:
    get:
      summary: Get link count
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count: { type: integer }
    post:
      summary: Create a short link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url: { type: string }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  url: { type: string }
                  link: { type: string }
        '400':
          description: Invalid URL